name: Build GrylParanoia

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozitáře
        uses: actions/checkout@v4

      - name: Nastavení Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Vygenerování Gradle Wrapperu (Tady se to vytvoří!)
        run: gradle wrapper

      - name: Povolení práv pro Gradle
        run: chmod +x ./gradlew

      - name: Kompilace módu (Build)
        run: ./gradlew build

      - name: Nahrání hotového .jar souboru
        uses: actions/upload-artifact@v4
        with:
          name: GrylParanoia-Mod
          path: build/libs/*.jar
